version: "3.5"
services:
  ${repository}:
    image: hatlonely/${repository}:${version}
    hostname: ${repository}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - ${repository}net

networks:
  ${repository}net:
    name: ${repository}net
